### ISSUE TITLE
Insert Image

### ISSUE THREAD

**Issue by minhnhat2807** [julianpoemp/ngx-jodit#31] opened 2024-04-24 15:57 UTC
Describe the issue as detailed as possible, in a way I can reproduce it easily.

![image](https://github.com/julianpoemp/ngx-jodit/assets/4848091/ba7f3ab6-4133-48e1-8258-41e9051fa5c8)

Issue on insert image https://github.julianpoemp.com/ngx-jodit/3.x/

Please answer additionally:

- Is this issue related to ngx-jodit or ngx-jodit-pro? - ngx-jodit 
- What version of the package - 3.1.2
- What Angular version are you using - 16

**Comment by julianpoemp** [comment] 2024-04-24 17:58
@minhnhat2807 thank you for reporting this issue. I was able to reproduce this error.

The problem here is a missing plugin called "resizer". So import it like the other plugins to your app:

````typescript
import 'jodit/esm/plugins/resizer/resizer.js';
````
[How to import plugins?](https://github.com/julianpoemp/ngx-jodit/blob/main/libs/ngx-jodit/README.md#how-to-import-plugins)

Since Jodit 4 all buttons are plugins themself. Some of theme are loaded by default other must be imported manually. It's not clear what plugin depends on other plugins so we have to do "try and error" and find the missing plugin using the error message.

I'll update the demo pages soon.

If the issue is solved, you can close it.

**Comment by minhnhat2807** [comment] 2024-04-25 02:05
thanks @julianpoemp the problem with image was resolved but I have concerns about another issue, if I used the custom config some icon cannot display and seem this config
`"uploader": {
    "insertImageAsBase64URI": true
  }`
  
  
![image](https://github.com/julianpoemp/ngx-jodit/assets/4848091/fd3693f7-5d48-498f-8bcf-9bb51112a69a)

`options: JoditConfig = {
    toolbarAdaptive: false,

    disablePlugins: 'video,wrap-nodes,xpath,speech-recognize,print,preview,class-span,ai-assistant',
    buttons:
      'bold,italic,underline,|,strikethrough,eraser,ul,ol,font,fontsize,paragraph,lineHeight,superscript,subscript,image,spellcheck,table,link,indent,outdent,left,brush,undo,redo,find'
  }`

**Comment by julianpoemp** [comment] 2024-04-25 06:33
I'm currently not on a computer so I can't check it out.

If some buttons don't show an icon it indicates a missing plugin. Go to "node_models/jodit/esm/plugins" and search for a folder named like the missing plugin. Import the js file like I recommended for the resizer plugin before.

**Comment by minhnhat2807** [comment] 2024-04-25 09:30
Thanks a lot, about the 
`"uploader": { "insertImageAsBase64URI": true }` seem we need to put every proper for that object

**Comment by julianpoemp** [comment] 2024-04-26 07:49
I'm closing this issue because it's solved. Please consider giving this repository a star :)

**Closed by julianpoemp** 2024-04-26 07:49 UTC
Labels: bug
