### ISSUE TITLE
Support for Jodit Pro OEM

### ISSUE THREAD

**Issue by cgraves09** [julianpoemp/ngx-jodit#5] opened 2023-06-22 14:42 UTC
Hi does this package support give the ability to pass in our license key for Jodit PRO?

**Comment by cgraves09** [comment] 2023-06-23 14:17
@julianpoemp Thank you for getting back to me so quick. So i added that in but it still shows the water mark and doesnt have any of the functionality of the pro.

**Comment by julianpoemp** [comment] 2023-06-23 14:55
@cgraves09 I found out that there is an extra npm package for jodit-pro [here](https://www.npmjs.com/package/jodit-pro). Because it's a different package from the normal Jodit package with it's own dependencies I'll release a new Angular library with Jodit Pro support. I'll contact you as soon as I have more information.

**Comment by cgraves09** [comment] 2023-06-23 14:57
@julianpoemp Amazing thank you so much

**Comment by julianpoemp** [comment] 2023-06-23 17:38
@cgraves09 I just released ngx-jodit-pro. You can find more information here:
https://www.npmjs.com/package/ngx-jodit-pro

If you provide a license key in the options it should work now. Please notice: I was able to test it only without a license key and can't say if it works for sure.

Please let me know if it works. In case of errors please send me the console output.

**Comment by cgraves09** [comment] 2023-06-26 17:15
@julianpoemp Awesome thank you. So i am getting
![Screenshot 2023-06-26 at 1 15 15 PM](https://github.com/julianpoemp/ngx-jodit/assets/53089867/455fd15b-ed85-461f-81d8-1cafc0926db7)
 an error from the console

**Comment by julianpoemp** [comment] 2023-06-26 17:18
@cgraves09 did you follow the installation instructions? Especially adding `node_modules/jodit-pro/build/jodit.js` to scripts

**Comment by cgraves09** [comment] 2023-06-26 17:27
@julianpoemp Yeah got it. Seems to be rendering now with the license and removing the watermark. Which is fantastic! Not sure if this is an issue but I am getting this type error. Not sure if its going to break anything.
![Screenshot 2023-06-26 at 1 27 22 PM](https://github.com/julianpoemp/ngx-jodit/assets/53089867/6a215ad1-8036-4393-8b7c-f5f02277976c)

**Comment by julianpoemp** [comment] 2023-06-26 17:33
@cgraves09 can you send me more of the error message, please? (click on the ">" left to "Uncaught" to expand it")

**Comment by cgraves09** [comment] 2023-06-26 17:37
![Screenshot 2023-06-26 at 1 37 03 PM](https://github.com/julianpoemp/ngx-jodit/assets/53089867/1ebdacc6-d4cd-40f6-932e-a3be4f7e490c)
Here is it expanded let me know if you want all the frames

**Comment by julianpoemp** [comment] 2023-06-26 17:45
@cgraves09 I think it's an error caused by Jodit.

I close this issue because the original problem was solved. If you like this package I would be happy if you give this repository a star 😄

**Closed by julianpoemp** 2023-06-26 17:45 UTC

**Comment by julianpoemp** [comment] 2023-06-26 18:30
@cgraves09 form controls? Do you think about buttons for the toolbar or plugins? You can access the jodit instance from ngx-jodit as described [here](https://github.com/julianpoemp/ngx-jodit/tree/main/libs/ngx-jodit-pro#using-jodit-pro-api) and use the Jodit API to add buttons or plugins (more information [here](https://xdsoft.net/jodit/pro/docs/how-to/create-plugin.md))

This project is just a wrapper for Jodit and I want to keep it light, at least for now.
