### ISSUE TITLE
ngx-jodit-pro:paste image copy from outlook

### ISSUE THREAD

**Issue by Yang-Jing-Hui** [julianpoemp/ngx-jodit#11] opened 2023-07-28 02:33 UTC
1. Copy the image from Outlook email 
2. Use Ctrl + V to paste the image to the Jodit editor
![image](https://github.com/julianpoemp/ngx-jodit/assets/139448915/b3b6b3e9-5f78-46d8-834b-c8b89de5db98)

Jodit-editor can not show the image.

package.json：
"@angular/cdk": "13.3.9",
"@angular/common": "13.3.11",
"@angular/compiler": "13.3.11",
"@angular/core": "13.3.11",
"jodit": "3.24.9",
"jodit-pro": "^1.3.40",
"ngx-jodit-pro": "^1.0.2",

I didn’t have this problem when I pasted the Outlook image on [the Jodit-pro official website demo](https://xdsoft.net/jodit/pro/
).

**Comment by julianpoemp** [comment] 2023-07-28 06:18
@Yang-Jing-Hui what's the console output? Any errors? Perhaps this is an issue related to CORS, because you're probably pasting an image from a public server to Jodit that is served on a local server.

If this isn't the issue please send me more information: Either...

a)... send me a link to a [stackblitz](https://stackblitz.com/) project to make it easy for me to reproduce this issue

b)... or send me all code related to your Jodit implementation (HTML snippet, TS snippet and the styles and scripts properties from angular.json/projects.json). Please make sure to not send personal information including your license key.

**Comment by Yang-Jing-Hui** [comment] 2023-07-31 03:04
@julianpoemp Thank you for replying me so quickly.
console without any error message.
[SampleCode](https://stackblitz.com/edit/angular-component-example-2pr8hf?file=.angular-cli.json)

![image](https://github.com/julianpoemp/ngx-jodit/assets/139448915/c9dff5b5-0485-4db4-83b9-84a2fe558c72)

**Comment by julianpoemp** [comment] 2023-08-04 10:03
I think it's solved. Closing it.

**Comment by Yang-Jing-Hui** [comment] 2023-09-08 07:14
I add  paste-from-word.js  in my scripts property of your angular.json/project.json:
This issue is still not resolved.
I originally thought it was because I didn't fill out the license for jodit-pro. I recently applied for it and added it, but it still didn't work.
![image](https://github.com/julianpoemp/ngx-jodit/assets/139448915/5abd0ef5-bfc7-420c-9e46-bd7a41dc9097)

**Comment by julianpoemp** [comment] 2023-09-08 07:44
@Yang-Jing-Hui you are currently using jodit, not jodit-pro. The plugins don't work and the license key doesn't have any affect. You see this on two points:

1.) There is no Jodit-Pro v3.
2.) With Jodit-Pro the water mark "powered by" on the right bottom corner is not visible.

Please make sure, that you have installed "ngx-jodit-pro" as described [here](https://github.com/julianpoemp/ngx-jodit/blob/v3.x/libs/ngx-jodit-pro/README.md). If you installed ngx-jodit ealier make sure it's completely removed using "npm remove ngx-jodit". In node_modules folder "ngx-jodit" shouldn't exist but "ngx-jodit-pro" should. HTML snippet should look like this:

````HTML
  <ngx-jodit-pro [(value)]="value" [options]="options"></ngx-jodit-pro>
````
If the problem still exists please send me your package.json content and the HTML snippet you are using to embed ngx-jodit-pro.

Reopening it. If it's solved please close this issue.

**Comment by julianpoemp** [comment] 2023-09-08 07:55
@Yang-Jing-Hui I re-checked ngx-jodit-pro demo v1 and I have the same issue even if I'm using jodit-pro. It's very strange. I'll investigate this.

**Comment by Yang-Jing-Hui** [comment] 2023-09-08 08:06
Should I open a new issue?

**Comment by julianpoemp** [comment] 2023-09-08 08:13
@julianpoemp no, I already re-opened it. Found the solution, releasing it in the next hour :)

**Closed** 2023-09-08 08:24 UTC

**Comment by julianpoemp** [comment] 2023-09-08 09:24
@julianpoemp new release ngx-jodit-pro@1.0.3 fixes this issue.

**Comment by julianpoemp** [comment] 2023-09-08 09:24
@Yang-Jing-Hui  new release ngx-jodit-pro@1.0.3 fixes this issue.
