### ISSUE TITLE
ngx-jodit-pro: Delete image error

### ISSUE THREAD

**Issue by Yang-Jing-Hui** [julianpoemp/ngx-jodit#16] opened 2023-09-27 01:31 UTC
If you use the **Delete** key on the keyboard to delete a picture, an error will occur.

![image](https://github.com/julianpoemp/ngx-jodit/assets/139448915/4a1d0122-c1ff-44c9-b6b7-4b71e84c0936)

global-error-handler.ts:46 TypeError: Node element must be in editor
    at n (node_modules\jodit-pro\build\jodit.js:1:60738)
    at ne.select (node_modules\jodit-pro\build\jodit.js:1:98880)
    at Ot.onDelete (node_modules\jodit-pro\build\jodit.js:1:369297)
    at HTMLDivElement.<anonymous> (node_modules\jodit-pro\build\jodit.js:1:366382)
    at HTMLDivElement.g (node_modules\jodit-pro\build\jodit.js:1:30503)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)

This seems to be a bug of jodit-pro, but it does not appear when I run the [jodit-pro demo](https://xdsoft.net/jodit/pro/#demo).

Package versions：
   "@angular/animations": "13.3.11",
    "@angular/cdk": "13.3.9",
    "@angular/common": "13.3.11",
    "@angular/compiler": "13.3.11",
    "@angular/core": "13.3.11",
    "jodit": "^3.24.9",
    "jodit-pro": "^1.3.40",
    "ngx-jodit-pro": "^1.0.6",

**Comment by julianpoemp** [comment] 2023-09-27 08:00
@Yang-Jing-Hui the official demo uses Jodit Pro Beta 2. Unfortunately I can't reproduce this issue using my demo-pro application and Jodit-Pro 1. Can You please explain each step you've taken to get this error? How did you insert the picture before?

**Comment by julianpoemp** [comment] 2023-09-27 10:09
@Yang-Jing-Hui I created an Demo Stackblitz project. Perhaps you can reproduce the issue there (don't add your license key):
https://stackblitz.com/edit/stackblitz-starters-bic4kq

**Comment by Yang-Jing-Hui** [comment] 2023-09-28 02:23
I used Microsoft Paint to select and copy the image, and then pasted it into the jodit editor.
Select the picture I just pasted in the jodit editor and press the Delete key on the keyboard.
![image](https://github.com/julianpoemp/ngx-jodit/assets/139448915/3a889292-f31f-4672-be32-4d91988b8d91)
![image](https://github.com/julianpoemp/ngx-jodit/assets/139448915/98cc1a71-c9ba-43c5-9b50-680917c2da37)

**Comment by Yang-Jing-Hui** [comment] 2023-09-28 03:59
I think it is jodit-pro issue.
[Reference](https://github.com/xdan/jodit/issues/973)

**Comment by julianpoemp** [comment] 2023-09-28 06:33
@Yang-Jing-Hui Yes, it's an Jodit-Pro issue. Closing this.

**Closed** 2023-09-28 06:34 UTC
